
import React, { ReactNode } from 'react';
import AppWrappers from './Wrappers';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oceanesia",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body id={'root'} className={inter.className}>
      <AppWrappers>{children}</AppWrappers>
      </body>
    </html>
  );
}